# Generated by Django 6.0.5 on 2026-05-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='cold_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='customs_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='destination_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='dispatcher_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='dispatcher_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='dispatcher_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='dispatcher_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='goods_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='goods_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='goods_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='hazardous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='insurance_covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='recipient_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='recipient_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='recipient_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
