# Generated by Django 6.0.5 on 2026-05-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
