# Generated by Django 6.0.5 on 2026-06-01 05:40
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('tracker', '0002_trackingevent_latitude_trackingevent_longitude'),
    ]
    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, default=uuid.uuid4),
        ),
    ]
