# Generated by Django 6.0.5 on 2026-05-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackingevent_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='handover_datetime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='handover_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='incoming_transporter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='outgoing_transporter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='qty_discrepancy_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='qty_dispatched',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='qty_received',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('manufactured', 'Manufactured'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('at_hub', 'At Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('handover', 'Handover')], max_length=50),
        ),
    ]
